### ISSUE TITLE
Using OTP to encrypt urls

### ISSUE THREAD

**Issue by khavishbhundoo** [mmeyer2k/dcrypt#17]
Hello,
I am trying to use OTP but obviously i am doing something wrong.

Here is part of my code 

https://pastebin.com/7aU2ZVdH

Thanks for the help and great library

**Comment by mmeyer2k** [comment]
I'm not sure if this is the only problem but in this block...
```php
    private function decrypt() {
        $plaintext = \Dcrypt\Otp::crypt($this->password,hex2bin($this->URL));
        return $plaintext;
    }
```

... the parameters are not in the correct order. Data should be first, password second.

**Comment by khavishbhundoo** [comment]
@mmeyer2k  Ahh that was stupid.What are your views on the implementation , my use case is to try to generate unique encrypted hash even for same plaintext.

**Comment by mmeyer2k** [comment]
Stream ciphers are good for that because they don't have IVs. But they also don't have checksums, so be careful!

**Comment by mmeyer2k** [comment]
Hey one more thing. If the size is of the output is important use base62 encoding instead of hex. It is a more compact representation of the binary and is still URL safe.

**Comment by khavishbhundoo** [comment]
I was thinking about base64 and then url encoding.

**Comment by mmeyer2k** [comment]
That works but base62 encoding will look better and in some cases will be more compact.

I like this one:

https://github.com/tuupola/base62
