### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by rantsh** [mmeyer2k/dcrypt#34]
After installing this library via composer, I was trying it out with the example provided in the readme file and got the error 

Steps to reproduce:

- install the library via composer
- Run the script below

```
<?php
require_once "vendor/autoload.php";
// Create a new random 32 byte key
$key = \Dcrypt\OpensslKey::create(32);

$encrypted = \Dcrypt\Aes::encrypt('a secret', $key);

$plaintext = \Dcrypt\Aes::decrypt($encrypted, $key);
```

- Produces the error below

```
PHP Fatal error:  Uncaught Dcrypt\Exceptions\InvalidKeyException: Key must be at least 2048 bytes and base64 encoded in /mnt/c/Users/rantsh/Documents/workspace/KOS-Projects/PHPMall/vendor/mmeyer2k/dcrypt/src/OpensslKey.php:136
Stack trace:
#0 /mnt/c/Users/rantsh/Documents/workspace/KOS-Projects/PHPMall/delete.php(4): Dcrypt\OpensslKey::create()
#1 {main}
  thrown in /mnt/c/Users/rantsh/Documents/workspace/KOS-Projects/PHPMall/vendor/mmeyer2k/dcrypt/src/OpensslKey.php on line 136
```

**Comment by mmeyer2k** [comment]
hello @rantsh 

Please try using the latest version of dcrypt (13.2.1). The 13.x versions handle keys much differently than the versions before.

![image](https://user-images.githubusercontent.com/1887431/101078116-5217db00-356b-11eb-8f89-0aba7796b68a.png)

**Comment by rantsh** [comment]
That worked, I guess i should've noticed the version constraint on the composer command. 

Thanks for the support, and for a VERY useful library

**Comment by mmeyer2k** [comment]
No problem! I'm glad you find it useful.

**Comment by mmeyer2k** [comment]
Also, FYI, if you are unable to update, in the version you are using you can generate a correct key by specifying `256` as the size parameter.
